# please see matrix-full.yml for meaning of each field
build-packages:
- label: ubuntu-22.04
  os: ubuntu-22.04
  package: deb
  check-manifest-suite: ubuntu-22.04-amd64
- label: rhel-9-arm64
  os: ubuntu-22.04-arm64
  image: rockylinux:9
  package: rpm
  package-type: el9
  check-manifest-suite: el9-arm64

build-images:
- label: ubuntu
  base-image: ubuntu:22.04
  package: deb
  artifact-from: ubuntu-22.04
- label: rhel
  base-image: registry.access.redhat.com/ubi9
  package: rpm
  rpm_platform: el9
  artifact-from: rhel-9
  artifact-from-alt: rhel-9-arm64
  docker-platforms: linux/amd64, linux/arm64

smoke-tests:
- label: ubuntu
- label: rhel

scan-vulnerabilities:
- label: ubuntu
- label: rhel

release-packages:
- label: rhel-9-arm64
  package: rpm
  artifact-from: rhel-9-arm64
  artifact-version: 9
  artifact-type: rhel
  artifact: kong.el9.arm64.rpm

release-images:
- label: ubuntu
  package: deb
- label: rhel
